import React from 'react';
import { AnalysisResult } from '../types';
import { BrainCircuit, ShieldAlert, CheckCircle2, AlertTriangle } from 'lucide-react';
import RiskBadge from './RiskBadge';

interface AIAnalysisProps {
  analysis: AnalysisResult | null;
  loading: boolean;
}

const AIAnalysis: React.FC<AIAnalysisProps> = ({ analysis, loading }) => {
  if (loading) {
    return (
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 animate-pulse">
        <div className="h-6 bg-slate-800 rounded w-1/3 mb-4"></div>
        <div className="space-y-3">
          <div className="h-4 bg-slate-800 rounded w-full"></div>
          <div className="h-4 bg-slate-800 rounded w-5/6"></div>
          <div className="h-4 bg-slate-800 rounded w-4/6"></div>
        </div>
      </div>
    );
  }

  if (!analysis) return null;

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden relative">
       <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none">
          <BrainCircuit size={120} className="text-morpho-500" />
       </div>
       
       <div className="p-6 border-b border-slate-800 bg-slate-850/50">
         <div className="flex items-center justify-between flex-wrap gap-4">
           <div className="flex items-center gap-3">
             <BrainCircuit className="text-morpho-400 w-6 h-6" />
             <h2 className="text-xl font-semibold text-white">AI Risk Auditor</h2>
           </div>
           <RiskBadge verdict={analysis.verdict} />
         </div>
       </div>

       <div className="p-6 space-y-6">
         <div>
           <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-2">Executive Summary</h3>
           <p className="text-slate-300 leading-relaxed text-lg">{analysis.summary}</p>
         </div>

         <div>
           <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-3">Identified Risk Factors</h3>
           <div className="grid gap-3">
             {analysis.riskFactors.map((factor, idx) => (
               <div key={idx} className="flex items-start gap-3 p-3 rounded-lg bg-slate-950/50 border border-slate-800/50">
                 <AlertTriangle className="w-5 h-5 text-orange-400 shrink-0 mt-0.5" />
                 <span className="text-slate-300 text-sm">{factor}</span>
               </div>
             ))}
           </div>
         </div>
         
         <div className="pt-4 border-t border-slate-800 flex items-center gap-2 text-xs text-slate-500">
            <ShieldAlert className="w-4 h-4" />
            <span>Analysis generated by Gemini 2.5 Flash. This is not financial advice. Always verify on-chain data.</span>
         </div>
       </div>
    </div>
  );
};

export default AIAnalysis;